name: Keepalive Workflow

on:
  schedule:
    - cron: '0 0 1 * *'   # 每月1号凌晨0点运行
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v1
